version: '2.20.3'
  # Run this file using `docker-compose up -d`, which starts the container at background.

services:
  app:
    image: ns3.43-gym:latest  # 替换为您想要使用的镜像名称，如 python:3.10 等
    container_name: ai-comm-net-ns3.43-gym  # 替换为您的容器名称
    volumes:
      - ../../workspace:/workspace  # 将宿主机的上一层目录中的 workspace 目录映射到容器内的 /workspace
    ports:
      - "7777:22"  # 将宿主机的 7777 端口映射到容器的 22 端口，供编程 IDE 链接
    environment:
      - EXAMPLE_ENV_VAR=value  # 可选的环境变量，替换为适合您的设置
    command: ["/bin/bash", "-c", "echo 'Hello, AI for Communication Networking'; tail -f /dev/null"]  # 保持容器后台运行并输出消息
    deploy:
      resources:
        limits:
          memory: 16g  # 限制容器的内存大小不超过 16GB
          cpus: "10.0"  # 限制容器占用 CPU 核数不超过 10 核

volumes:
  workspace_data:
    driver: local
